### ISSUE TITLE
Which convention do the camera extrinsics follow? (OpenGL or OpenCV)

### ISSUE THREAD

**Issue by andrewsonga** [facebookresearch/cop3d#2]
Hello,

I was wondering which camera conventions do the camera extrinsics stored inside "frame_annotations.jgz" follow?

My guess would be that the cameras are defined in OpenGL convention following Pytorch3D, but I just wanted to be sure.

Thank you in advance!

**Comment by shapovalov** [comment]
The matrices are indeed world-to-camera transform in Pytorch3D NDC format.
I.e. `X_cam = (X_world @ R + T)` for extrinsics.
`K @ X_cam` would give the NDC coordinates in [−1, 1] × [−1, 1] (assuming a square image).
More info: https://pytorch3d.org/docs/cameras

**Comment by andrewsonga** [comment]
So just to clarify, the camera extrinsics are defined in the OpenGL convention, and NOT in the OpenCV convention correct?

**Comment by shapovalov** [comment]
PyTorch3D cameras are different from OpenCV:
1) both coordinate systems are right-handed but X and Y axes are flipped when you go from one to another,
2) R is transposed,
3) intrinsics are in normalised coordinates, not in pixels.


See the conversion function: https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/camera_conversions.py#L62

I cannot say for sure if OpenGL cameras are same.

**Comment by andrewsonga** [comment]
The link for the conversion function appears to be private. I cannot access it.

**Comment by shapovalov** [comment]
Should be fixed now.

**Comment by andrewsonga** [comment]
Thank you! I'm closing this issue as it is resolved.
