### ISSUE TITLE
Implementation of TrackRF

### ISSUE THREAD

**Issue by andrewsonga** [facebookresearch/cop3d#5]
First of all, thank you for releasing this large, amazing dataset. I am having a lot of fun playing around with it.

I was wondering if you are planning to release an official implementation of TrackRF. The offset prediction network seems to be very involved and I wanted to have a baseline implementation for dynamic scene reconstruction.

**Comment by shapovalov** [comment]
Thanks Andrew. The first author of TrackRF has moved on, so realistically, we won’t have capacity to prepare the release. However, implementing some variant of it should be easy in Implicitron. I think the heaviest part is preparing the data (extracting DensePose and optical flow); the model is fairly simple.
